### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 för Windows-skrivbord
  description: Microsoft Application Virtualization Hosting 5.1 för Windows-datorer följer policyn för fast livscykel.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "864172"
name: Microsoft Application Virtualization Hosting 5.1 för Windows-skrivbord
summary: >+
  Microsoft Application Virtualization Hosting 5.1 för Windows-datorer följer [policyn](/lifecycle/policies/fixed) för fast livscykel.


  Detta gäller följande versioner: för Windows-skrivbord

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Länkar \n* [Produktinformation](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Upplagor \n* för Windows-skrivbord"
