### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization hosting 4.6 för Windows-skrivbord
  description: Microsoft Application Virtualization Hosting 4.6 för Windows-datorer följer policyn för fast livscykel.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153942"
name: Microsoft Application Virtualization hosting 4.6 för Windows-skrivbord
summary: >+
  Microsoft Application Virtualization Hosting 4.6 för Windows-datorer följer policyn för [fast](/lifecycle/policies/fixed) livscykel.


  Detta gäller för följande utgåvor: för Windows-skrivbordsenhet

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Länkar \n* [Information om produkt och migrering](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service pack-policy](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Eftersom App-V 4.6-klienten använder App-V 4.5-servern fortsätter App-V 4.5-servern att stödjas enligt datumen för livscykeln gällande App-V 4.6 när den används med den App-V 4.6-klient som stöds.\n\n## <a name=\"editions\"></a>Utgåvor \n* for Windows-skrivbordsenhet"
