### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 följer principen om fast livscykel.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511296"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 följer principen om [fast](/lifecycle/policies/fixed) livscykel.



  > [!IMPORTANT]

  > Support för den här produkten har upphört. Se migreringsvägledningen nedan.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Länkar \n* [Vägledning för migrering](/mem/configmgr/core/migration/planning-for-migration)\n* [Ytterligare vägledning om migrering](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
