### YamlMime:Lifecycle
metadata:
  title: Konfigurationshanteraren för Microsoft System Center 2012 R2
  description: Konfigurationshanteraren för Microsoft System Center 2012 R2 följer policyn för fast livscykel.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: b9a1c0fa5804c5929f39f72816e86e49c739d281
  ms.sourcegitcommit: 8465b0fa45ee2c451d1f1eaf7be9a1544cdad17f
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 03/12/2021
  ms.locfileid: "1462925"
name: Konfigurationshanteraren för Microsoft System Center 2012 R2
summary: >+
  Konfigurationshanteraren för Microsoft System Center 2012 R2 följer policyn för [fast](/lifecycle/policies/fixed) livscykel.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Länkar \n* [Service pack-policy](/lifecycle/policies/fixed#service-packs)\n* [Dokumentation för konfigurationshanteraren](/mem/configmgr/core/misc/online-documentation)\n* [Vägledning för migrering](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
