### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization hosting 4.6 för Windows-skrivbord
  description: Microsoft Application Virtualization Hosting 4.6 för Windows-datorer följer policyn för fast livscykel.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 8a32729ae5fbf7f57a14b6a6ec048c7a1f412a52
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935468"
name: Microsoft Application Virtualization hosting 4.6 för Windows-skrivbord
summary: >+
  Microsoft Application Virtualization Hosting 4.6 för Windows-datorer följer policyn för [fast](/lifecycle/policies/fixed) livscykel.


  Detta gäller för följande utgåvor: för Windows-skrivbordsenhet

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Länkar \n* [Information om produkt och migrering](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service pack-policy](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Eftersom App-V 4.6-klienten använder App-V 4.5-servern fortsätter App-V 4.5-servern att stödjas enligt datumen för livscykeln gällande App-V 4.6 när den används med den App-V 4.6-klient som stöds.\n\n## <a name=\"editions\"></a>Utgåvor \n* for Windows-skrivbordsenhet"
