### YamlMime:Lifecycle
metadata:
  title: Virtualisering av SoftGrid-program
  description: Virtualisering av SoftGrid-program följer principen för fast livscykel.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "841426"
name: Virtualisering av SoftGrid-program
summary: >
  Virtualisering av SoftGrid-program följer principen för [fast](/lifecycle/policies/fixed) livscykel.


  Detta gäller följande utgåvor: 4.1 för stationära datorer, 4.2 för stationära datorer, för Terminal Services 4.1


  > [!IMPORTANT]

  > Stödet har upphört. Se migreringsvägledning nedan.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Länkar \n* [Vägledning för migrering](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Upplagor \n* 4.1 för stationära datorer\n* 4.2 för stationära datorer\n* för terminaltjänster 4.1"
